name: CI/CD Workflow

on:
  push:
    branches:
      - master

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.13.0

      - name: Install NPM Modules
        run: npm ci

      - name: Execute Tests
        run: npm run test:cov

      - name: Build and Publish Docker Image
        run: bash ../scripts/publish-docker-image.sh

      - name: Upload Test Coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Docker
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u $DOCKER_USER --password-stdin
          docker pull rntvicente/circleci-build-node:18.13.0
          docker run -d --name currency-conversion-api rntvicente/circleci-build-node:18.13.0
